In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
res = ''
with open('./starter/sudokus_start.txt', 'r+') as f:
    res += f.read()

In [9]:
sudokus = np.array([[int(j) for j in i] for i in res.split()])

In [14]:
s = sudokus[0].reshape((9,9))
print(s)

[[0 0 3 0 2 0 6 0 0]
 [9 0 0 3 0 5 0 0 1]
 [0 0 1 8 0 6 4 0 0]
 [0 0 8 1 0 2 9 0 0]
 [7 0 0 0 0 0 0 0 8]
 [0 0 6 7 0 8 2 0 0]
 [0 0 2 6 0 9 5 0 0]
 [8 0 0 2 0 3 0 0 9]
 [0 0 5 0 1 0 3 0 0]]


In [13]:
n = 3
i = 5
j = 2

s[i,j]

6

In [15]:
col -> s[:,j] 

array([3, 0, 1, 8, 0, 6, 2, 0, 5])

In [16]:
row -> s[i,:]

array([0, 0, 6, 7, 0, 8, 2, 0, 0])

In [19]:

[[(j//3, i//3) for j in range(9)] for i in range(9)]

[[(0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (1, 0), (2, 0), (2, 0), (2, 0)],
 [(0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (1, 0), (2, 0), (2, 0), (2, 0)],
 [(0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (1, 0), (2, 0), (2, 0), (2, 0)],
 [(0, 1), (0, 1), (0, 1), (1, 1), (1, 1), (1, 1), (2, 1), (2, 1), (2, 1)],
 [(0, 1), (0, 1), (0, 1), (1, 1), (1, 1), (1, 1), (2, 1), (2, 1), (2, 1)],
 [(0, 1), (0, 1), (0, 1), (1, 1), (1, 1), (1, 1), (2, 1), (2, 1), (2, 1)],
 [(0, 2), (0, 2), (0, 2), (1, 2), (1, 2), (1, 2), (2, 2), (2, 2), (2, 2)],
 [(0, 2), (0, 2), (0, 2), (1, 2), (1, 2), (1, 2), (2, 2), (2, 2), (2, 2)],
 [(0, 2), (0, 2), (0, 2), (1, 2), (1, 2), (1, 2), (2, 2), (2, 2), (2, 2)]]